# Generated by Django 6.0.3 on 2026-03-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
